parameters:
    darvin_bot_detector.security.configuration.class: Darvin\BotDetectorBundle\Security\SecurityConfiguration

services:
    darvin_bot_detector.security.configuration:
        class: %darvin_bot_detector.security.configuration.class%
        tags:
            - { name: darvin_config.configuration }
            - { name: darvin_admin.security_configuration }
