menu:
    group: modules
    icons:
        main: bundles/darvinbotdetector/images/admin/detected_bot_main.png
route_blacklist:
    - batch-delete
    - copy
    - delete
    - edit
    - new
    - update-property
sortable_fields:
    date:         ~
    botType:      ~
    ip:           ~
    url:          ~
    responseCode: ~
form:
    filter:
        fields:
            dateFrom: ~
            dateTo:   ~
            botType:
                compare_strict: false
            ip:
                compare_strict: false
            url:
                compare_strict: false
            responseCode:
                compare_strict: false
view:
    index:
        action_widgets:
            show_link: ~
        fields:
            date:         ~
            botType:      ~
            ip:           ~
            url:          ~
            responseCode: ~
    show:
        action_widgets: ~
        fields:
            date:         ~
            botType:      ~
            ip:           ~
            url:          ~
            responseCode: ~
